// <auto-generated />
namespace Loss_Prevention.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class BuyTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BuyTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202001121318040_Buy-Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
